### ISSUE TITLE
有部分不是傳承字形

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [lxgw/LxgwClearGothic#1]
按照傳承字形的標準：https://github.com/ichitenfont/inheritedglyphs
但是有的部分沒改變。

**Comment by UltimateAmitieKaiNiC** [comment]
像是：音章意辛童妾龍商帝箙章竟竞旁亲良
像是窗、窻、聰、總、驄、蔥、傯、璁的「囪」不作「囱」。
乑部件是傳承字形從三「人」。左「人」捺筆變點。中作「亻」。

**Comment by lxgw** [comment]
由於時間關係，這些涉及字數比較多的部件暫時沒改，所以可能會有一些不符合傳承字形標準文件的字形。

尤其是「音」「妾」等字上的「立」形，據不完全統計，包含以下漢字：

辛音龍宰梓辜锌莘辞辟辣辤鋅骍騂辭辨辧辦辩辫辮辯辟僻劈噼壁嬖擗澼擘檗璧臂避甓癖薜襞譬躄鐴鐾鸊薛孽糵蘖亲新薪澵噺榇櫬親襯偣竟谙喑揞意暗歆韴韵瘖韶諳闇韻響黯幟樴熾織職識竜竞競境镜鏡竸章嫜嶂幛彰漳獐鄣障暲樟璋遧瘴蟑鏱鱆麞赣贛童僮噇幢徸憧撞潼曈橦瞳穜艟蕫鐘嚨壟壠寵攏瀧隴龐曨朧櫳瓏矓礱籠聾襲龔龕讋豅躘靇龗亥侅刻劾该咳垓奒孩峐阂骇核欬氦赅痎荄該賅閡駭骸商啇谪嘀嫡摘滴敵適镝謫蹢鏑帝谛啻啼崹揥渧缔楴禘締蒂諦蹄鍗鶙旁傍谤嵭徬滂榜牓膀磅镑蒡螃謗鎊妾唼接椄翣霎毅墒熵噫镱鐿

有時間會改。

**Comment by UltimateAmitieKaiNiC** [comment]
希望未來可能會改變傳承字形。

**Comment by UltimateAmitieKaiNiC** [comment]
窗、窻、聰、總、驄、蔥、傯、璁的應該作「囪」不作「囱」。

**Comment by lxgw** [comment]
> 窗、窻、聰、總、驄、蔥、傯、璁的應該作「囪」不作「囱」。

「囪」「聚」「眾」已修復。

**Comment by UltimateAmitieKaiNiC** [comment]
> 由於時間關係，這些涉及字數比較多的部件暫時沒改，所以可能會有一些不符合傳承字形標準文件的字形。
> 
> 尤其是「音」「妾」等字上的「立」形，據不完全統計，包含以下漢字：
> 
> 辛音龍宰梓辜锌莘辞辟辣辤鋅骍騂辭辨辧辦辩辫辮辯辟僻劈噼壁嬖擗澼擘檗璧臂避甓癖薜襞譬躄鐴鐾鸊薛孽糵蘖亲新薪澵噺榇櫬親襯偣竟谙喑揞意暗歆韴韵瘖韶諳闇韻響黯幟樴熾織職識竜竞競境镜鏡竸章嫜嶂幛彰漳獐鄣障暲樟璋遧瘴蟑鏱鱆麞赣贛童僮噇幢徸憧撞潼曈橦瞳穜艟蕫鐘嚨壟壠寵攏瀧隴龐曨朧櫳瓏矓礱籠聾襲龔龕讋豅躘靇龗亥侅刻劾该咳垓奒孩峐阂骇核欬氦赅痎荄該賅閡駭骸商啇谪嘀嫡摘滴敵適镝謫蹢鏑帝谛啻啼崹揥渧缔楴禘締蒂諦蹄鍗鶙旁傍谤嵭徬滂榜牓膀磅镑蒡螃謗鎊妾唼接椄翣霎毅墒熵噫镱鐿
> 
> 有時間會改。

但咅部的不變，第一筆畫的橫點有時間會更新呢。

**Comment by UltimateAmitieKaiNiC** [comment]
「顧」沒變呀！

**Comment by lxgw** [comment]
> 「顧」沒變呀！

「顧」「啓」「肇」「綮」等字會在下個版本更新。

**Comment by UltimateAmitieKaiNiC** [comment]
> 幛

但是「閡」是傳承的呀！

**Comment by UltimateAmitieKaiNiC** [comment]
意的億和憶沒修改

**Comment by lxgw** [comment]
> 億、憶、臆、薏、癔、塱沒修改

已修改，版本号 v0.204

**Comment by function98** [comment]
![image](https://user-images.githubusercontent.com/68038518/104849147-2f773100-5923-11eb-881b-cf215d9c7da3.png)
追加：箙墜

**Comment by lapomme** [comment]
「風」部件也需要改。「丿」→「一」
![image](https://user-images.githubusercontent.com/27000939/104857856-15f8c980-58d0-11eb-8a79-a41c9ae22982.png)

**Comment by function98** [comment]
追加：敷湧
![image](https://user-images.githubusercontent.com/68038518/105032880-59029a80-5a92-11eb-98cb-8f523f432346.png)

**Comment by function98** [comment]
追加：率薇
![image](https://user-images.githubusercontent.com/68038518/105128097-471a0980-5b1d-11eb-86a2-27d2c13a3953.jpeg)

**Comment by function98** [comment]
追加：夅降韋𡶷曻桀桝偉傑粦舜葦違韌搩暐瑋禕僲粼舞褘隣嶙憐潾磔緯衛遴韑𥻘儛燐璘膦諱辚瞬瞵磷闈韓韔𬭸竵翷韘韙韞轔韛韜韡鏻鳞鱗麟炁既厩旣塈慨溉概槩墍漑槪簪蠶埖硴錵勗昪蘰枲
![image](https://user-images.githubusercontent.com/68038518/105364111-bab03980-5c37-11eb-802d-87495f9f9c46.png)

**Comment by UltimateAmitieKaiNiC** [comment]
還有更多草字頭的

**Comment by function98** [comment]
> 還有更多草字頭的

草字头我觉得大可不必，现在这样就已经能足够区分了

**Comment by lapomme** [comment]
> 還有更多草字頭的

![image](https://user-images.githubusercontent.com/27000939/105536914-f84bab80-5ca5-11eb-8e9a-9e660ab80190.png)

**Comment by UltimateAmitieKaiNiC** [comment]
「乎」的也有稍微改一下

**Comment by function98** [comment]
追加：廠耕籍
![image](https://user-images.githubusercontent.com/68038518/106002601-49b3ca80-60ec-11eb-85d0-eb999c0a59db.png)

**Comment by function98** [comment]
好吧，我觉得旣（U+65E3）漑（U+6F11）槪（U+69EA）的「皀」部件根本没必要修改
![image](https://user-images.githubusercontent.com/68038518/106153237-4a666280-61b9-11eb-94a4-34705c74c0ab.png)

**Comment by function98** [comment]
追加：猶
![image](https://user-images.githubusercontent.com/68038518/106275381-b22bb480-6270-11eb-813c-1745d1d3ccc9.png)

**Comment by UltimateAmitieKaiNiC** [comment]
還有「煙」

**Comment by function98** [comment]
追加：澀
![image](https://user-images.githubusercontent.com/68038518/106355366-50cc1a00-6332-11eb-8939-f553c4c29528.png)

**Comment by function98** [comment]
> 還有「煙」

应该说所有带「垔」部件的字

**Comment by UltimateAmitieKaiNiC** [comment]
追加：環

**Comment by UltimateAmitieKaiNiC** [comment]
需修改的：丩部件所有的字、并部件所有的字、㓞部件部分的字、𬙙部件所有的字、納、祆、櫜、頖、竊、膂等部件
有些字型從「曰」，不從「日」的字有些字相連著成「日」也算是常見寫法嗎？

**Comment by lxgw** [comment]
近期會重啓這個項目，原有的傳承晰黑推倒重來，參考早期鉛字印刷字形寫法，不再全盤參照「傳承字形標準化文件」。
