### ISSUE TITLE
癒（U+7652）、涙（U+6D99）、戻（U+623B）仍为新字体（形）

### ISSUE THREAD

**Issue by function98** [lxgw/LxgwClearGothic#2]
这三个字需要尽快改正

**Comment by lxgw** [comment]
有点日本用的字暂时没改，如涙（U+6D99）、戻（U+623B）等。因为在中文里已经有对应的正体。

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwClearGothic/projects/1

已纪录，下个版本修复。

**Comment by function98** [comment]
追加：墜邃顧敷
