### ISSUE TITLE
希腊字母与西里尔字母有很大的问题

### ISSUE THREAD

**Issue by function98** [lxgw/LxgwClearGothic#4]
这些字母彼此间距特别大，根本无法将词汇区分开，不知道能否进行修正

**Comment by Egnale99** [comment]
> 这些字母彼此间距特别大

首先這不是間距特別大，而是字形寬設定在了 2048（相當於全形字寬）。
再者，日本字型基本上都是這個德性（？）

**Comment by function98** [comment]
> > 这些字母彼此间距特别大
> 
> 
> 
> 首先這不是間距特別大，而是字形寬設定在了 2048（相當於全形字寬）。
> 
> 再者，日本字型基本上都是這個德性（？）

那就把字宽收窄就可以解决这个问题了，收窄到多少可以参照同字体的拉丁字母

**Comment by lxgw** [comment]
日本字体基本上就这样，希俄字母都是全角，还有中国的很多字体也是这样。

**Comment by function98** [comment]
> 日文字体基本上就这样，希俄字母都是全角，还有很多中文字体也是这样。

不过我还是希望能尽早修复这个问题，毕竟因为一些特殊原因我可能需要俄文，字母拉太开看着很费劲的

**Comment by function98** [comment]
现在是v0.204，西里尔字母修正了，希腊字母仍未修正
