### ISSUE TITLE
【版本 0.204】全形逗號問題

### ISSUE THREAD

**Issue by Egnale99** [lxgw/LxgwClearGothic#6]
不知爲何，用作 Google Chrome 瀏覽器顯示字型時，全形逗號會顯示成半形逗號。而在其他地方顯示便沒有這問題。
　　另外，這個問題在這字型的歷史版本中**並沒出現過**。

（附同一段內容在 Google Chrome 瀏覽器與記事本上的顯示對比圖）
![スクリーンショット (76)](https://user-images.githubusercontent.com/64576145/104871215-73028700-5985-11eb-89dd-92b79128ec3b.png)

　　2021 年 1 月 18 日，15 時 30 分補充：後來發現不只有逗號，就連問號、嘆號、冒號、分號、甚至括號等都有這種問題。望能盡速解決！

**Comment by lxgw** [comment]
已修復，請在 GitHub 重新下載。
