### ISSUE TITLE
部分汉字需要调整

### ISSUE THREAD

**Issue by Marcus98T** [lxgw/LxgwClearGothic#8]
俞部的比例需要调整一点，要向上移动一点。红色是缺字。

<img width="1359" alt="Screenshot 2021-03-08 at 23 24 05" src="https://user-images.githubusercontent.com/10541683/110342973-f62b8980-8066-11eb-94b7-6a303f1bb99d.png">

还有，请改"兪偸喩婾楡"。我真的不知道俞字上面可不可以作"人"还是"入"。
<img width="718" alt="Screenshot 2021-03-08 at 23 57 48" src="https://user-images.githubusercontent.com/10541683/110346037-2163a800-806a-11eb-91a1-aa125cb5c9ed.png">

另外，Regular 和 Book 在我Mac上抱怨这两种字体是重复的。可能是同样的PostScript名，请查看一下。

最后，本字体在我的Mac不支持竖排文字。这包括您其他的字体。
<img width="177" alt="Screenshot 2021-03-08 at 23 32 12" src="https://user-images.githubusercontent.com/10541683/110342774-c11f3700-8066-11eb-9b6a-ee5f1b0a0f7e.png">

**Comment by Marcus98T** [comment]
"違"要改成这个：
<img width="628" alt="Screenshot 2021-03-09 at 13 51 43" src="https://user-images.githubusercontent.com/10541683/110425118-ccae4480-80de-11eb-912d-254d9fe07f43.png">

本字体有异体字，所以合拼这两个绿色的地方。

**Comment by CL-Jeremy** [comment]
> 还有，请改"兪偸喩婾楡"。我真的不知道俞字上面可不可以作"人"还是"入"。

这些字属于日文兼容字体，可以参考 Mac 系统下北京汉仪与字游工坊合作的 Hiragino Sans GB，这五个字均从「入」。这五个字在日常繁简输入时并不会用到，需要输入传承汉字的日语用户必须直接使用中文输入法。这是 Unicode 的限制（如果修改则会造成在基本多语平面内的一字多码，在这一点上的取舍值得商榷。我个人并不排斥修改日文部分的写法）。

至于竖排的问题，经查看，字体里没有 `vrt2` 表，可以参考思源黑体，直接建立写上 `lookup SUB_0;` 使用 `vert` 表的列表即可（如果不能引用现有替换表，则复制全部内容到新表）。很不幸，我的 Glyphs 还存在 bug，生成的字体还是无法竖排（具体表现为，其他所有字体都会显示一个空的 `aalt` 表，而本字体并不会，这可能可以说明本字体的特性表存在一定的问题）

**Comment by Marcus98T** [comment]
> 这五个字均从「入」。这五个字在日常繁简输入时并不会用到，需要输入传承汉字的日语用户必须直接使用中文输入法。

我Mac的手写可以得到这五字，但是我想其他人（非Mac或iOS使用者）没有这个特权。

<img width="380" alt="Screenshot 2021-03-09 at 18 40 04" src="https://user-images.githubusercontent.com/10541683/110458644-f7ac8e80-8106-11eb-91c3-b37e2a22a013.png">

**Comment by CL-Jeremy** [comment]
> > 这五个字在日常繁简输入时并不会用到，需要输入传承汉字的日语用户必须直接使用中文输入法。
> 
> 我Mac的手写可以得到这五字，但是我想其他人（非Mac或iOS使用者）没有这个特权。
> <img alt="Screenshot 2021-03-09 at 18 40 04" width="380" src="https://user-images.githubusercontent.com/10541683/110458644-f7ac8e80-8106-11eb-91c3-b37e2a22a013.png">

这里的输入法指的是日文输入法，中文输入法一般不存在使用这五个字的必要。当然，如果专门选字的话，市面上收录这些字的输入法不在少数，无论是截图中的 RIME（鼠须管）还是系统自带的输入法都有，只不过在编码上属于非常用字而已。日文输入法则是确确实实无法输入中文字形的这五字，因为 Shift-JIS 中不存在这五个字的编码。我没有查 Adobe-Japan 的编码，但某些专业版日文字体可以通过 OpenType feature 中通过异体字选择器支持多个地区的字形支持。
![Snipaste_2021-03-09_11-55-29](https://user-images.githubusercontent.com/1714243/110461331-95846700-80cf-11eb-8098-df86a4fcf36c.png)

本字体应该说并没有特别面向日文用户，但确确实实是以日文标准的字体为起点开始制作的，而这个标准本身以矛盾（指常用汉字表内与表外的种种对立）著称。这五个字当中，四个属于表外字，仅有喻（喩，今常用「諭」）字一字于 2010 年加入常用汉字表，可以通行新字体偏旁（但这一变更在现有字体中并没有普及开来），另外四个字实属罕见。一点明体确实已经将其改成了与「喻」同样的字形，但本字体无论如何取舍都不会影响到中文圈用户。个人对变更与否持观望态度，只不过举例说明一下，现今的商业中文字体中基本没有对这五个字动手的，可以说是一种惯例吧。

**Comment by CL-Jeremy** [comment]
刚刚对比了一点明体的替换表格式，没有一点区别，怪哉

**Comment by lxgw** [comment]
近期會重啓這個項目，原有的傳承晰黑推倒重來，參考早期鉛字印刷字形寫法，不再全盤參照「傳承字形標準化文件」。
